const form = document.querySelector('#auditForm')
const scoreValue = document.querySelector('#scoreValue')
const scoreTitle = document.querySelector('#scoreTitle')
const scoreSummary = document.querySelector('#scoreSummary')
const fixList = document.querySelector('#fixList')
const copyButton = document.querySelector('#copyResults')
const emailLink = document.querySelector('#emailResults')
const businessName = document.querySelector('#businessName')
const websiteUrl = document.querySelector('#websiteUrl')

function getAuditState() {
  const checks = [...form.querySelectorAll('input[name="score"]')]
  const checked = checks.filter(input => input.checked)
  const missing = checks.filter(input => !input.checked)
  const score = checked.reduce((total, input) => total + Number(input.value), 0)
  const fixes = missing.map(input => input.dataset.fix).filter(Boolean).slice(0, 5)
  return { score, fixes }
}

function getRating(score) {
  if (score >= 82) {
    return {
      title: 'Strong site, cleanup only',
      summary: 'The basics are working. The best paid move is a narrow polish pass or a small automation around leads and follow-up.',
    }
  }
  if (score >= 58) {
    return {
      title: 'Good base, clear repair opportunity',
      summary: 'The site probably does some things well, but there are enough gaps for a focused repair pass to make sense.',
    }
  }
  if (score >= 32) {
    return {
      title: 'High-value rebuild candidate',
      summary: 'The site likely needs clearer positioning, stronger mobile flow, and a simpler path to contact or booking.',
    }
  }
  return {
    title: 'Audit not started',
    summary: 'Check the boxes that are already true. The missing items become your highest-value fix list.',
  }
}

function buildResultText() {
  const { score, fixes } = getAuditState()
  const name = businessName.value.trim() || 'Website'
  const url = websiteUrl.value.trim() || 'No URL provided'
  const fixText = fixes.length ? fixes.map((fix, index) => `${index + 1}. ${fix}`).join('\n') : 'No urgent fixes selected.'
  return `${name} website audit\nURL: ${url}\nScore: ${score}/100\n\nPriority fixes:\n${fixText}\n\nGenerated by Tate Lyman's free website audit.`
}

function updateAudit() {
  const { score, fixes } = getAuditState()
  const rating = getRating(score)
  scoreValue.textContent = String(score)
  scoreTitle.textContent = rating.title
  scoreSummary.textContent = rating.summary

  fixList.replaceChildren()
  if (fixes.length === 0) {
    const item = document.createElement('li')
    item.textContent = score > 0 ? 'No urgent fixes selected. The next step is a polish pass or automation idea.' : 'Fill out the audit to generate a prioritized repair list.'
    fixList.append(item)
  }
  else {
    for (const fix of fixes) {
      const item = document.createElement('li')
      item.textContent = fix
      fixList.append(item)
    }
  }

  const body = encodeURIComponent(`${buildResultText()}\n\nI want help with this site.`)
  emailLink.href = `mailto:lymantate2@gmail.com?subject=Website%20audit%20request&body=${body}`
}

form.addEventListener('input', updateAudit)

copyButton.addEventListener('click', async () => {
  const text = buildResultText()
  try {
    await navigator.clipboard.writeText(text)
    copyButton.textContent = 'Copied'
    window.setTimeout(() => {
      copyButton.textContent = 'Copy result'
    }, 1600)
  }
  catch {
    copyButton.textContent = 'Select text manually'
    window.setTimeout(() => {
      copyButton.textContent = 'Copy result'
    }, 1600)
  }
})

updateAudit()
