const form = document.querySelector('#vibeCheckForm')
const scoreValue = document.querySelector('#scoreValue')
const scoreTitle = document.querySelector('#scoreTitle')
const scoreSummary = document.querySelector('#scoreSummary')
const fixList = document.querySelector('#fixList')
const copyButton = document.querySelector('#copyResults')
const emailLink = document.querySelector('#emailResults')
const appName = document.querySelector('#appName')
const appUrl = document.querySelector('#appUrl')
const builderStack = document.querySelector('#builderStack')

function getCheckState() {
  const checks = [...form.querySelectorAll('input[name="score"]')]
  const checked = checks.filter(input => input.checked)
  const missing = checks.filter(input => !input.checked)
  const score = checked.reduce((total, input) => total + Number(input.value), 0)
  const risks = missing.map(input => input.dataset.fix).filter(Boolean).slice(0, 6)
  return { score, risks }
}

function getRating(score) {
  if (score >= 86) {
    return {
      title: 'Strong launch posture',
      summary: 'The obvious production risks are mostly covered. A paid pass would focus on proof, edge cases, and verifying implementation details.',
    }
  }
  if (score >= 66) {
    return {
      title: 'Launchable after focused cleanup',
      summary: 'The app has a decent base, but the missing checks are exactly where AI-built apps tend to fail after real users arrive.',
    }
  }
  if (score >= 36) {
    return {
      title: 'Do not launch without a risk pass',
      summary: 'There are enough missing production checks that auth, data, payment, or usage-cost failures are realistic.',
    }
  }
  return {
    title: 'Safety check not started',
    summary: 'Check the boxes that are already true. Missing items become the highest-risk launch blockers.',
  }
}

function buildResultText() {
  const { score, risks } = getCheckState()
  const name = appName.value.trim() || 'AI-built app'
  const url = appUrl.value.trim() || 'No URL provided'
  const stack = builderStack.value.trim() || 'Stack not provided'
  const riskText = risks.length
    ? risks.map((risk, index) => `${index + 1}. ${risk}`).join('\n')
    : 'No urgent risks selected by the self-check.'

  return `${name} vibe-coded app safety check
URL/repo: ${url}
Builder or stack: ${stack}
Safety score: ${score}/100

Priority risks:
${riskText}

Generated by Tate Lyman's free vibe-coded app safety check.`
}

function updateCheck() {
  const { score, risks } = getCheckState()
  const rating = getRating(score)
  scoreValue.textContent = String(score)
  scoreTitle.textContent = rating.title
  scoreSummary.textContent = rating.summary

  fixList.replaceChildren()
  if (risks.length === 0) {
    const item = document.createElement('li')
    item.textContent = score > 0
      ? 'No urgent risks selected. The next step is manual verification of the implementation.'
      : 'Fill out the check to generate a prioritized launch-risk list.'
    fixList.append(item)
  }
  else {
    for (const risk of risks) {
      const item = document.createElement('li')
      item.textContent = risk
      fixList.append(item)
    }
  }

  const body = encodeURIComponent(`${buildResultText()}\n\nI want help reviewing or fixing these risks.`)
  emailLink.href = `mailto:lymantate2@gmail.com?subject=Vibe-coded%20app%20safety%20check&body=${body}`
}

form.addEventListener('input', updateCheck)

copyButton.addEventListener('click', async () => {
  const text = buildResultText()
  try {
    await navigator.clipboard.writeText(text)
    copyButton.textContent = 'Copied'
    window.setTimeout(() => {
      copyButton.textContent = 'Copy result'
    }, 1600)
  }
  catch {
    copyButton.textContent = 'Select text manually'
    window.setTimeout(() => {
      copyButton.textContent = 'Copy result'
    }, 1600)
  }
})

updateCheck()
